language: cpp
compiler:
  - gcc

script: make


deploy:
  provider: pages
  skip_cleanup: true
  # github_token: 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 
  keep_history: true
  on:
    branch: main
 
