language: cpp
compiler:
  - gcc

script: make


deploy:
  provider: pages
  skip_cleanup: true
  github_token: "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"
  keep_history: true
  on:
    branch: main
 
