name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  defaults:
    run:
        working-directory: ./build
    runs-on: ubuntu-latest
   

    steps:
    # - uses: actions/cpp-
    # - name: hello
     - run: /build/hello
   # - name: make
   #   run: make
   # - name: make check
    #  run: make check
    # - name: make distcheck
     # run: make distcheck
