name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
 hello:
   
       
    runs-on: ubuntu-latest
   

    steps:
    # - uses: actions/cpp-
    # - name: hello
     - run: cd /
           ls -l
            # chmod +x hello

   # - name: make
   #   run: make
   # - name: make check
    #  run: make check
    # - name: make distcheck
     # run: make distcheck
